const axios = require('axios');
const { getAdReplyScript } = require("./adreply");
const config = require("../config");

module.exports = async (socket, from, msg, args, command) => {
  const text = args.join(" ");
  const name = msg.pushName || "Invocador";
  const adReply = getAdReplyScript();

  if (!text) {
    return await socket.sendMessage(from, {
      text: `✳️ Ingresa tu pregunta\nEjemplo: *${config.PREFIX + command}* ¿quién inventó WhatsApp?`,
      contextInfo: adReply.contextInfo
    });
  }

  await socket.sendMessage(from, { react: { text: "🕳️", key: msg.key } });

  const prompt = await getPrompt();
  let result = "";

  try {
    result = await luminaiQuery(text, name, prompt);
    result = cleanResponse(result);
  } catch (e) {
    console.error("Error Luminai:", e);
    try {
      result = await perplexityQuery(text, prompt);
    } catch (e2) {
      console.error("Error Perplexity:", e2);
      result = "No se obtuvo respuesta de los servicios.";
    }
  }

  await socket.sendMessage(from, {
    text: result,
    contextInfo: adReply.contextInfo
  }, { quoted: msg });

  await socket.sendMessage(from, { react: { text: "✨", key: msg.key } });
};

async function getPrompt() {
  try {
    const res = await fetch('https://raw.githubusercontent.com/elrebelde21/LoliBot-MD/main/src/text-chatgpt.txt');
    return await res.text();
  } catch {
    return 'Eres un asistente inteligente';
  }
}

function cleanResponse(text) {
  if (!text) return '';
  return text
    .replace(/Maaf, terjadi kesalahan saat memproses permintaan Anda/g, '')
    .replace(/Generated by BLACKBOX\.AI.*?https:\/\/www\.blackbox\.ai/g, '')
    .replace(/and for API requests replace https:\/\/www\.blackbox\.ai with https:\/\/api\.blackbox\.ai/g, '')
    .trim();
}

async function luminaiQuery(q, user, prompt) {
  const { data } = await axios.post('https://luminai.my.id', {
    content: q,
    user: user,
    prompt: prompt,
    webSearchMode: true
  });
  return data.result;
}

async function perplexityQuery(q, prompt) {
  const { data } = await axios.get('https://api.perplexity.ai/chat', {
    params: { query: q, context: prompt }
  });
  return data.response;
}
