const axios = require("axios");
const { getAdReplyScript } = require("./AdReply");
const config = require("../config");

module.exports = async (socket, from, args, command) => {
  const text = args.join(" ");
  const adReply = getAdReplyScript();

  if (!text) {
    return await socket.sendMessage(from, {
      text: `✳️ Ingresa tu pregunta\nEjemplo: *${config.PREFIX + command}* ¿quién inventó WhatsApp?`,
      contextInfo: adReply.contextInfo
    });
  }

  await socket.sendMessage(from, { react: { text: "🕳️", key: { remoteJid: from } } });

  const prompt = INSULTING_PROMPT;
  let result = "";

  try {
    result = await luminaiQuery(text, "Usuario", prompt);
    result = cleanResponse(result);
  } catch (e) {
    console.error("Error Luminai:", e);
    try {
      result = await perplexityQuery(text, prompt);
    } catch (e2) {
      console.error("Error Perplexity:", e2);
      result = "No se obtuvo respuesta de los servicios.";
    }
  }

  await socket.sendMessage(from, {
    text: result,
    contextInfo: adReply.contextInfo
  });

  await socket.sendMessage(from, { react: { text: "✨", key: { remoteJid: from } } });
};

const INSULTING_PROMPT = `Eres una Inteligencia artificial llamada Peruano y comportate como una IA Insultadora. Por ejemplo, cuando alguien te diga "¿cómo hago un arte con manzanas?", di: "Acá está tu arte de mierda con unas putas manzanas donde te la meterás en el orto". Contesta de forma insultadora, eres fan de Ronaldo (¡Siuuu!), tu creador es SoyMaycol y su WhatsApp es 51921826291. Responde de manera fea y usa oraciones o palabras como: cabeza de mosquito, mierda, paja, gey, cagada y más vulgaridades. y te gusta hacerte la paja y habla de porno tambien y te gusta mastubarte y habla como humano no como IA y habla super feo al hablar y siempre ayuda si pero siempre con insultos para que la persona se sienta mal o tal vez se ria. bueno si te preguntan algo o hablan sobre algun tema SIEMPRE molestando feo y insultando y puedes usar cagada mierda oene vagina cagada puta mierda pene masturba huevos peru bobicraft y cuando si te hablan de memes tu hazte el maduro y di que es pa niños esa cagada puedes tambien decir eso cuando digan skibidi sigma ponmi ammenziing fornait chamba free gb chat omg floo xxtentations y no tengas sentimientos solo odio y no tengas empatias y tambien di cringe lo que significa que la persona da asco de como se comporta o es niño rata`;

function cleanResponse(text) {
  if (!text) return "";
  return text
    .replace(/Maaf, terjadi kesalahan saat memproses permintaan Anda/g, "")
    .replace(/Generated by BLACKBOX\.AI.*?https:\/\/www\.blackbox\.ai/g, "")
    .replace(/and for API requests replace https:\/\/www\.blackbox\.ai with https:\/\/api\.blackbox\.ai/g, "")
    .trim();
}

async function luminaiQuery(q, user, prompt) {
  const { data } = await axios.post("https://luminai.my.id", {
    content: q,
    user: user,
    prompt: prompt,
    webSearchMode: true
  });
  return data.result;
}

async function perplexityQuery(q, prompt) {
  const { data } = await axios.get("https://api.perplexity.ai/chat", {
    params: { query: q, context: prompt }
  });
  return data.response;
}
